/// Link to a specific section of the Lua manual.
macro_rules! lua_section {
  ($version:literal, $section:literal) => {
    concat!(
      "https://www.lua.org/manual/",
      $version,
      "/manual.html#",
      $section
    )
  };
}

/// A definition in the Lua manual
macro_rules! lua_def {
  ($version:literal => $name:literal) => {
    (
      $name,
      concat!(
        "https://www.lua.org/manual/",
        $version,
        "/manual.html#pdf-",
        $name
      ),
    )
  };
}

/// A list of built-in Lua definitions and a link to their documentation.
pub const LUA_DEFINITIONS: &[(&str, &str)] = &[
  ("coroutine", lua_section!("5.1", "5.2")),
  ("debug", lua_section!("5.1", "5.9")),
  ("math", lua_section!("5.1", "5.6")),
  ("package", lua_section!("5.1", "5.3")),
  ("string", lua_section!("5.1", "5.4")),
  ("table", lua_section!("5.1", "5.5")),
  ("bit32", lua_section!("5.2", "6.7")),
  ("utf8", lua_section!("5.3", "6.5")),
  // Lua 5.1
  lua_def!("5.1" => "debug.getfenv"),
  lua_def!("5.1" => "debug.setfenv"),
  lua_def!("5.1" => "getfenv"),
  lua_def!("5.1" => "loadstring"),
  lua_def!("5.1" => "package.loaders"),
  lua_def!("5.1" => "setfenv"),
  lua_def!("5.1" => "table.maxn"),
  lua_def!("5.1" => "unpack"),
  // Lua 5.2
  lua_def!("5.2" => "_G"),
  lua_def!("5.2" => "_VERSION"),
  lua_def!("5.2" => "assert"),
  lua_def!("5.2" => "bit32.arshift"),
  lua_def!("5.2" => "bit32.band"),
  lua_def!("5.2" => "bit32.bnot"),
  lua_def!("5.2" => "bit32.bor"),
  lua_def!("5.2" => "bit32.btest"),
  lua_def!("5.2" => "bit32.bxor"),
  lua_def!("5.2" => "bit32.extract"),
  lua_def!("5.2" => "bit32.lrotate"),
  lua_def!("5.2" => "bit32.lshift"),
  lua_def!("5.2" => "bit32.replace"),
  lua_def!("5.2" => "bit32.rrotate"),
  lua_def!("5.2" => "bit32.rshift"),
  lua_def!("5.2" => "collectgarbage"),
  lua_def!("5.2" => "coroutine.create"),
  lua_def!("5.2" => "coroutine.resume"),
  lua_def!("5.2" => "coroutine.running"),
  lua_def!("5.2" => "coroutine.status"),
  lua_def!("5.2" => "coroutine.wrap"),
  lua_def!("5.2" => "coroutine.yield"),
  lua_def!("5.2" => "debug.debug"),
  lua_def!("5.2" => "debug.gethook"),
  lua_def!("5.2" => "debug.getinfo"),
  lua_def!("5.2" => "debug.getlocal"),
  lua_def!("5.2" => "debug.getmetatable"),
  lua_def!("5.2" => "debug.getregistry"),
  lua_def!("5.2" => "debug.getupvalue"),
  lua_def!("5.2" => "debug.join"),
  lua_def!("5.2" => "debug.sethook"),
  lua_def!("5.2" => "debug.setlocal"),
  lua_def!("5.2" => "debug.setmetatable"),
  lua_def!("5.2" => "debug.setupvalue"),
  lua_def!("5.2" => "debug.traceback"),
  lua_def!("5.2" => "debug.upvalueid"),
  lua_def!("5.2" => "dofile"),
  lua_def!("5.2" => "error"),
  lua_def!("5.2" => "getmetatable"),
  lua_def!("5.2" => "ipairs"),
  lua_def!("5.2" => "load"),
  lua_def!("5.2" => "loadfile"),
  lua_def!("5.2" => "math.abs"),
  lua_def!("5.2" => "math.acos"),
  lua_def!("5.2" => "math.asin"),
  lua_def!("5.2" => "math.atan"),
  lua_def!("5.2" => "math.atan2"),
  lua_def!("5.2" => "math.ceil"),
  lua_def!("5.2" => "math.cos"),
  lua_def!("5.2" => "math.cosh"),
  lua_def!("5.2" => "math.deg"),
  lua_def!("5.2" => "math.exp"),
  lua_def!("5.2" => "math.floor"),
  lua_def!("5.2" => "math.fmod"),
  lua_def!("5.2" => "math.frexp"),
  lua_def!("5.2" => "math.huge"),
  lua_def!("5.2" => "math.ldexp"),
  lua_def!("5.2" => "math.log"),
  lua_def!("5.2" => "math.log10"),
  lua_def!("5.2" => "math.max"),
  lua_def!("5.2" => "math.min"),
  lua_def!("5.2" => "math.modf"),
  lua_def!("5.2" => "math.pi"),
  lua_def!("5.2" => "math.pow"),
  lua_def!("5.2" => "math.rad"),
  lua_def!("5.2" => "math.random"),
  lua_def!("5.2" => "math.randomseed"),
  lua_def!("5.2" => "math.sin"),
  lua_def!("5.2" => "math.sinh"),
  lua_def!("5.2" => "math.sqrt"),
  lua_def!("5.2" => "math.tan"),
  lua_def!("5.2" => "math.tanh"),
  lua_def!("5.2" => "next"),
  lua_def!("5.2" => "package.config"),
  lua_def!("5.2" => "package.loaded"),
  lua_def!("5.2" => "package.path"),
  lua_def!("5.2" => "package.preload"),
  lua_def!("5.2" => "package.searchpath"),
  lua_def!("5.2" => "pairs"),
  lua_def!("5.2" => "pcall"),
  lua_def!("5.2" => "print"),
  lua_def!("5.2" => "rawequal"),
  lua_def!("5.2" => "rawget"),
  lua_def!("5.2" => "rawlen"),
  lua_def!("5.2" => "rawset"),
  lua_def!("5.2" => "require"),
  lua_def!("5.2" => "select"),
  lua_def!("5.2" => "setmetatable"),
  lua_def!("5.2" => "string.byte"),
  lua_def!("5.2" => "string.char"),
  lua_def!("5.2" => "string.dump"),
  lua_def!("5.2" => "string.find"),
  lua_def!("5.2" => "string.format"),
  lua_def!("5.2" => "string.gmatch"),
  lua_def!("5.2" => "string.gsub"),
  lua_def!("5.2" => "string.len"),
  lua_def!("5.2" => "string.lower"),
  lua_def!("5.2" => "string.match"),
  lua_def!("5.2" => "string.rep"),
  lua_def!("5.2" => "string.reverse"),
  lua_def!("5.2" => "string.sub"),
  lua_def!("5.2" => "string.upper"),
  lua_def!("5.2" => "table.concat"),
  lua_def!("5.2" => "table.insert"),
  lua_def!("5.2" => "table.pack"),
  lua_def!("5.2" => "table.remove"),
  lua_def!("5.2" => "table.sort"),
  lua_def!("5.2" => "table.unpack"),
  lua_def!("5.2" => "tonumber"),
  lua_def!("5.2" => "tostring"),
  lua_def!("5.2" => "type"),
  lua_def!("5.2" => "xpcall"),
  // Lua 5.3
  lua_def!("5.3" => "coroutine.isyieldable"),
  lua_def!("5.3" => "string.pack"),
  lua_def!("5.3" => "string.packsize"),
  lua_def!("5.3" => "string.unpack"),
  lua_def!("5.3" => "table.move"),
  lua_def!("5.3" => "utf8.char"),
  lua_def!("5.3" => "utf8.charpattern"),
  lua_def!("5.3" => "utf8.codepoint"),
  lua_def!("5.3" => "utf8.codes"),
  lua_def!("5.3" => "utf8.len"),
  lua_def!("5.3" => "utf8.offset"),
  // Lua 5.5
  lua_def!("5.5" => "table.create"),
];
