name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clone
      uses: actions/checkout@v4

    - name: ⚒️ Build
      run: |
        sudo apt update && sudo apt install -y musl-tools
        rustup target add x86_64-unknown-linux-musl
        cargo build --release --target x86_64-unknown-linux-musl

    - name: 📤 Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: Binaries
        path: ./target/x86_64-unknown-linux-musl/release/faqbot-cc
        retention-days: 1
